{% set name = "pytest-profiling" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c3a7ee88bcd9a3723c01b4e885ea9da6d070d62110d800e51ddd7f35ea82cf7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-git
  run:
    - gprof2dot
    - pytest
    - python
    - setuptools
    - six

test:
  imports:
    - pytest_profiling

about:
  home: https://github.com/manahl/pytest-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Profiling plugin for py.test

extra:
  recipe-maintainers:
    - pmgrafe
